// <auto-generated />
using System;
using FormsWebApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormsWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230426181536_BugFix")]
    partial class BugFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormsWebApp.Models.CLogin", b =>
                {
                    b.Property<string>("e_mail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("e_mail");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormsWebApp.Models.Field", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Formid")
                        .HasColumnType("int");

                    b.Property<string>("dataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("form_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("required")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("Formid");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("FormsWebApp.Models.Form", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_e_mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Form");
                });

            modelBuilder.Entity("FormsWebApp.Models.Field", b =>
                {
                    b.HasOne("FormsWebApp.Models.Form", null)
                        .WithMany("fields")
                        .HasForeignKey("Formid");
                });

            modelBuilder.Entity("FormsWebApp.Models.Form", b =>
                {
                    b.Navigation("fields");
                });
#pragma warning restore 612, 618
        }
    }
}
